[package]
name = "git-doorman"
version = "0.1.0"
edition = "2021"
description = "Deny unwanted text entry to your git index"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
memchr = "2.7.4"
shlex = "1.3.0"
